name: Simple CI job

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print message to console
        run: |
          current_date_time=$(date)
          echo "Current date and time: $current_date_time"
